POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "muthu_lingam",
  "name": "Muthulingam",
  "password": "@Lingam3269",
  "gender": "male",
  "location": "Chennai"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "muthu_lingam",
  "password": "@Lingam3269"
}

###
PUT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}